[[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

# [[main]]
#   name = "Posts"
#   weight = 300
#   identifier = "posts"
#   url = "/post/"

[[main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"

[[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"


# [[main]]
#   name = "Certifications"
#   weight = 520
#   identifier = "certifications"
#   url = "/certifications/"
